language.en=英文
language.zh=簡體中文
language.zh-tw=繁體中文
message.info.title=信息
message.warn.title=警告
message.error.title=錯誤
settings.tab.general=常規
settings.tab.patch=補丁
settings.SelectLanguage.label=語言
settings.PatchAssistant2J.path=補丁助手路徑
settings.PatchAssistant2J.label=補丁助手
settings.patch.nameTemplate=名稱模板
settings.patch.readme.label=說明文件
settings.patch.readme.fileName=文件名稱
settings.patch.readme.contentTemplate=內容模板
settings.patch.extConfig.label=擴展配置
actions.patch.GenPatchPackageAction.title=生成補丁
actions.patch.GenPatchPackageAction.description=生成補丁包
actions.patch.GenPatchPackageAction.generate=生成
actions.patch.GenPatchPackageAction.cancel=取消
actions.patch.GenPatchPackageAction.preview-readme=預覽說明文件
actions.patch.GenPatchPackageAction.dialog.title=預覽說明文件
actions.patch.GenPatchPackageAction.dialog.copy-to-clipboard=拷貝到剪切板
actions.patch.GenPatchPackageAction.description.title=說明
actions.patch.GenPatchPackageAction.treeFilterType.label=過濾：
actions.patch.GenPatchPackageAction.treeFilterType.project=項目文件
actions.patch.GenPatchPackageAction.treeFilterType.change=變更文件
actions.patch.GenPatchPackageAction.treeFilterType.editor=編輯文件
actions.patch.GenPatchPackageAction.treeFilterType.selected=已選文件
actions.patch.GenPatchPackageAction.treeFilterType.jar=Jar文件
actions.patch.GenPatchPackageAction.config.generalTitle=常規
actions.patch.GenPatchPackageAction.config.fileName=文件名：
actions.patch.GenPatchPackageAction.config.outputFolder=輸出目錄：
actions.patch.GenPatchPackageAction.config.cover=是否覆蓋
actions.patch.GenPatchPackageAction.config.compress=是否壓縮
actions.patch.GenPatchPackageAction.config.includePath=包含路徑
actions.patch.GenPatchPackageAction.config.addModLabel=添加更新標識
actions.patch.GenPatchPackageAction.config.beforeTitle=生成之前
actions.patch.GenPatchPackageAction.config.buildType.label=編譯類型
actions.patch.GenPatchPackageAction.config.buildType.default=默認
actions.patch.GenPatchPackageAction.config.buildType.file=文件
actions.patch.GenPatchPackageAction.config.buildType.module=模塊
actions.patch.GenPatchPackageAction.config.buildType.project=項目
actions.patch.GenPatchPackageAction.config.afterTitle=生成之後
actions.patch.GenPatchPackageAction.config.openOutputFolder=打開輸出目錄
actions.patch.GenPatchPackageAction.config.openPatchAssistant2J=打開補丁替換
actions.patch.GenPatchPackageAction.buildFailedWarnMsg=編譯失敗，請手動編譯
actions.patch.GenPatchPackageAction.notFoundOutputFile=未找到文件%s的輸出文件，可以先編譯在試
actions.file.OpenOutputFileAction.title=打開輸出的文件
actions.file.OpenOutputFileAction.description=打開輸出的文件
actions.file.OpenOutputFileInExplorerAction.title=資源管理器中打開輸出文件
actions.file.OpenOutputFileInExplorerAction.description=資源管理器中打開輸出文件
actions.java.CopyTargetPathProvider.title=可能的應用路徑
